import type {
  AccountRecord,
  AccountsPayload,
  ApiKeysPayload,
  EventRecord,
  JobSnapshot,
  ProviderTarget,
  ProxyPayload,
} from "@/lib/app-types";

function createTargetState(target: ProviderTarget, overrides: Partial<AccountRecord["targetStates"]["tavily"]> = {}): AccountRecord["targetStates"]["tavily"] {
  return {
    target,
    status: "ready",
    hasArtifact: false,
    artifactId: null,
    artifactType: null,
    artifactPreview: null,
    lastResultAt: null,
    lastErrorCode: null,
    skipReason: null,
    ...overrides,
  };
}

export const sampleJob: JobSnapshot = {
  job: {
    id: 17,
    status: "running",
    runMode: "headed",
    need: 5,
    parallel: 2,
    maxAttempts: 9,
    successCount: 2,
    failureCount: 1,
    skipCount: 1,
    launchedCount: 4,
    startedAt: "2026-03-18T07:20:00.000Z",
    pausedAt: null,
    completedAt: null,
    lastError: null,
    targets: ["tavily", "chatgpt"],
  },
  activeAttempts: [
    {
      id: 201,
      accountId: 1,
      accountEmail: "alpha@outlook.com",
      status: "running",
      stage: "extract_api_key",
      proxyNode: "Tokyo-01",
      proxyIp: "34.91.22.10",
      errorCode: null,
      errorMessage: null,
      startedAt: "2026-03-18T07:23:00.000Z",
      completedAt: null,
      target: "chatgpt",
      sequenceIndex: 2,
    },
  ],
  recentAttempts: [
    {
      id: 198,
      accountId: 4,
      accountEmail: "delta@outlook.com",
      status: "failed",
      stage: "oauth_redirect",
      proxyNode: "Seoul-02",
      proxyIp: "52.11.12.44",
      errorCode: "oauth-timeout",
      errorMessage: "OAuth redirect timed out",
      startedAt: "2026-03-18T07:18:00.000Z",
      completedAt: "2026-03-18T07:19:00.000Z",
      target: "tavily",
      sequenceIndex: 1,
    },
    {
      id: 197,
      accountId: 2,
      accountEmail: "beta@outlook.com",
      status: "completed",
      stage: "done",
      proxyNode: "Tokyo-01",
      proxyIp: "34.91.22.10",
      errorCode: null,
      errorMessage: null,
      startedAt: "2026-03-18T07:10:00.000Z",
      completedAt: "2026-03-18T07:14:00.000Z",
      target: "tavily",
      sequenceIndex: 1,
    },
  ],
  eligibleCount: 22,
  completedTargetSteps: 6,
  totalTargetSteps: 10,
};

export const sampleEvents: EventRecord[] = [
  {
    type: "attempt.updated",
    timestamp: "2026-03-18T07:24:20.000Z",
    payload: {
      attemptId: 201,
      stage: "extract_api_key",
      proxyNode: "Tokyo-01",
    },
  },
  {
    type: "job.updated",
    timestamp: "2026-03-18T07:22:00.000Z",
    payload: {
      status: "running",
      successCount: 2,
      launchedCount: 4,
    },
  },
];

export const sampleAccounts = {
  total: 3,
  page: 1,
  pageSize: 20,
  summary: {
    ready: 1,
    linked: 1,
    failed: 1,
  },
  groups: ["default", "linked", "failed-pool"],
  rows: [
    {
      id: 1,
      microsoftEmail: "alpha@outlook.com",
      passwordPlaintext: "pass-456",
      passwordMasked: "****s456",
      hasApiKey: false,
      importedAt: "2026-03-18T07:00:00.000Z",
      updatedAt: "2026-03-18T07:23:00.000Z",
      importSource: "manual",
      lastUsedAt: null,
      lastResultStatus: "ready",
      lastResultAt: null,
      lastErrorCode: null,
      skipReason: null,
      groupName: "default",
      disabledAt: null,
      targetStates: {
        tavily: createTargetState("tavily"),
        chatgpt: createTargetState("chatgpt"),
      },
    },
    {
      id: 2,
      microsoftEmail: "beta@outlook.com",
      passwordPlaintext: "pass-789",
      passwordMasked: "****s789",
      hasApiKey: true,
      importedAt: "2026-03-18T06:55:00.000Z",
      updatedAt: "2026-03-18T07:15:00.000Z",
      importSource: "manual",
      lastUsedAt: "2026-03-18T07:12:00.000Z",
      lastResultStatus: "succeeded",
      lastResultAt: "2026-03-18T07:14:00.000Z",
      lastErrorCode: null,
      skipReason: "linked_api_key",
      groupName: "linked",
      disabledAt: null,
      targetStates: {
        tavily: createTargetState("tavily", {
          status: "succeeded",
          hasArtifact: true,
          artifactId: 1,
          artifactType: "api_key",
          artifactPreview: "tvly-prod••••",
          lastResultAt: "2026-03-18T07:14:00.000Z",
          skipReason: "linked_api_key",
        }),
        chatgpt: createTargetState("chatgpt"),
      },
    },
    {
      id: 3,
      microsoftEmail: "gamma@outlook.com",
      passwordPlaintext: "pass-111",
      passwordMasked: "****x111",
      hasApiKey: false,
      importedAt: "2026-03-18T06:30:00.000Z",
      updatedAt: "2026-03-18T07:05:00.000Z",
      importSource: "manual",
      lastUsedAt: "2026-03-18T06:59:00.000Z",
      lastResultStatus: "failed",
      lastResultAt: "2026-03-18T07:01:00.000Z",
      lastErrorCode: "password-invalid",
      skipReason: null,
      groupName: "failed-pool",
      disabledAt: null,
      targetStates: {
        tavily: createTargetState("tavily", {
          status: "failed",
          lastResultAt: "2026-03-18T07:01:00.000Z",
          lastErrorCode: "password-invalid",
        }),
        chatgpt: createTargetState("chatgpt", {
          status: "succeeded",
          hasArtifact: true,
          artifactId: 2,
          artifactType: "access_token",
          artifactPreview: "sess-••••z9Q",
          lastResultAt: "2026-03-18T07:02:00.000Z",
        }),
      },
    },
  ],
} satisfies AccountsPayload;

export const sampleApiKeys: ApiKeysPayload = {
  total: 2,
  page: 1,
  pageSize: 20,
  summary: {
    active: 1,
    revoked: 1,
  },
  rows: [
    {
      id: 1,
      accountId: 2,
      microsoftEmail: "beta@outlook.com",
      target: "tavily",
      artifactType: "api_key",
      preview: "tvly-prod••••af3x",
      status: "active",
      extractedAt: "2026-03-18T07:14:00.000Z",
      lastVerifiedAt: "2026-03-18T07:16:00.000Z",
      metadataJson: null,
    },
    {
      id: 2,
      accountId: 7,
      microsoftEmail: "omega@outlook.com",
      target: "chatgpt",
      artifactType: "access_token",
      preview: "sess-••••mm9p",
      status: "revoked",
      extractedAt: "2026-03-17T15:40:00.000Z",
      lastVerifiedAt: "2026-03-18T00:10:00.000Z",
      metadataJson: "{\"provider\":\"microsoft\"}",
    },
  ],
};

export const sampleProxies: ProxyPayload = {
  settings: {
    subscriptionUrl: "https://example.com/subscription.yaml",
    groupName: "Auto",
    routeGroupName: "Global",
    checkUrl: "https://www.gstatic.com/generate_204",
    timeoutMs: 1000,
    maxLatencyMs: 480,
    apiPort: 9090,
    mixedPort: 7890,
    serverHost: "127.0.0.1",
    serverPort: 9090,
    defaultRunMode: "headed",
    defaultNeed: 5,
    defaultParallel: 2,
    defaultMaxAttempts: 9,
  },
  selectedName: "Tokyo-01",
  nodes: [
    {
      id: 1,
      nodeName: "Tokyo-01",
      isSelected: true,
      lastStatus: "active",
      lastLatencyMs: 184,
      lastEgressIp: "34.91.22.10",
      lastCountry: "Japan",
      lastCity: "Tokyo",
      lastOrg: "ExampleNet",
      lastCheckedAt: "2026-03-18T07:20:00.000Z",
      lastSelectedAt: "2026-03-18T07:18:00.000Z",
      success24h: 8,
    },
    {
      id: 2,
      nodeName: "Seoul-02",
      isSelected: false,
      lastStatus: "warning",
      lastLatencyMs: 531,
      lastEgressIp: "52.11.12.44",
      lastCountry: "South Korea",
      lastCity: "Seoul",
      lastOrg: "TransitCloud",
      lastCheckedAt: "2026-03-18T07:19:00.000Z",
      lastSelectedAt: null,
      success24h: 2,
    },
  ],
};
