import type {
  AccountExtractorHistoryPayload,
  AccountExtractorSettings,
  AccountRecord,
  AccountsPayload,
  ApiKeyRecord,
  ApiKeysPayload,
  EventRecord,
  JobSnapshot,
  ProxyPayload,
} from "@/lib/app-types";

export const sampleJob: JobSnapshot = {
  job: {
    id: 17,
    status: "running",
    runMode: "headed",
    need: 5,
    parallel: 2,
    maxAttempts: 9,
    successCount: 2,
    failureCount: 1,
    skipCount: 1,
    launchedCount: 4,
    autoExtractSources: ["zhanghaoya", "shankeyun"],
    autoExtractQuantity: 2,
    autoExtractMaxWaitSec: 45,
    autoExtractAccountType: "outlook",
    startedAt: "2026-03-18T07:20:00.000Z",
    pausedAt: null,
    completedAt: null,
    lastError: null,
  },
  activeAttempts: [
    {
      id: 201,
      accountId: 1,
      accountEmail: "alpha@outlook.com",
      status: "running",
      stage: "extract_api_key",
      proxyNode: "Tokyo-01",
      proxyIp: "34.91.22.10",
      errorCode: null,
      errorMessage: null,
      startedAt: "2026-03-18T07:23:00.000Z",
      completedAt: null,
    },
  ],
  recentAttempts: [
    {
      id: 198,
      accountId: 4,
      accountEmail: "delta@outlook.com",
      status: "failed",
      stage: "oauth_redirect",
      proxyNode: "Seoul-02",
      proxyIp: "52.11.12.44",
      errorCode: "oauth-timeout",
      errorMessage: "OAuth redirect timed out",
      startedAt: "2026-03-18T07:18:00.000Z",
      completedAt: "2026-03-18T07:19:00.000Z",
    },
    {
      id: 197,
      accountId: 2,
      accountEmail: "beta@outlook.com",
      status: "completed",
      stage: "done",
      proxyNode: "Tokyo-01",
      proxyIp: "34.91.22.10",
      errorCode: null,
      errorMessage: null,
      startedAt: "2026-03-18T07:10:00.000Z",
      completedAt: "2026-03-18T07:14:00.000Z",
    },
  ],
  eligibleCount: 22,
  autoExtractState: {
    phase: "waiting",
    enabledSources: ["zhanghaoya", "shankeyun"],
    accountType: "outlook",
    currentRoundTarget: 2,
    acceptedCount: 1,
    rawAttemptCount: 2,
    attemptBudget: 5,
    inFlightCount: 1,
    remainingWaitSec: 31,
    maxWaitSec: 45,
    startedAt: "2026-03-18T07:24:00.000Z",
    lastProvider: "zhanghaoya",
    lastMessage: "账号鸭 accepted 1 usable account(s)",
    updatedAt: "2026-03-18T07:24:32.000Z",
  },
};

export const sampleEvents: EventRecord[] = [
  {
    type: "attempt.updated",
    timestamp: "2026-03-18T07:24:20.000Z",
    payload: {
      attemptId: 201,
      stage: "extract_api_key",
      proxyNode: "Tokyo-01",
    },
  },
  {
    type: "job.updated",
    timestamp: "2026-03-18T07:22:00.000Z",
    payload: {
      status: "running",
      successCount: 2,
      launchedCount: 4,
    },
  },
];

export const sampleAccounts = {
  total: 3,
  page: 1,
  pageSize: 20,
  summary: {
    ready: 1,
    linked: 1,
    failed: 0,
    disabled: 1,
  },
  groups: ["default", "linked", "failed-pool"],
  rows: [
    {
      id: 1,
      microsoftEmail: "alpha@outlook.com",
      passwordPlaintext: "pass-456",
      passwordMasked: "****s456",
      proofMailboxProvider: "moemail",
      proofMailboxAddress: "alpha-proof@mail-us.707079.xyz",
      proofMailboxId: "mailbox-alpha-001",
      hasApiKey: false,
      importedAt: "2026-03-18T07:00:00.000Z",
      updatedAt: "2026-03-18T07:23:00.000Z",
      importSource: "manual",
      accountSource: "manual",
      sourceRawPayload: null,
      lastUsedAt: null,
      lastResultStatus: "ready",
      lastResultAt: null,
      lastErrorCode: null,
      skipReason: null,
      groupName: "default",
      disabledAt: null,
      disabledReason: null,
    },
    {
      id: 2,
      microsoftEmail: "beta@outlook.com",
      passwordPlaintext: "pass-789",
      passwordMasked: "****s789",
      proofMailboxProvider: "moemail",
      proofMailboxAddress: "beta-proof@mail-us.707079.xyz",
      proofMailboxId: "mailbox-beta-002",
      hasApiKey: true,
      importedAt: "2026-03-18T06:55:00.000Z",
      updatedAt: "2026-03-18T07:15:00.000Z",
      importSource: "manual",
      accountSource: "manual",
      sourceRawPayload: null,
      lastUsedAt: "2026-03-18T07:12:00.000Z",
      lastResultStatus: "succeeded",
      lastResultAt: "2026-03-18T07:14:00.000Z",
      lastErrorCode: null,
      skipReason: "linked_api_key",
      groupName: "linked",
      disabledAt: null,
      disabledReason: null,
    },
    {
      id: 3,
      microsoftEmail: "gamma@outlook.com",
      passwordPlaintext: "pass-111",
      passwordMasked: "****x111",
      proofMailboxProvider: null,
      proofMailboxAddress: null,
      proofMailboxId: null,
      hasApiKey: false,
      importedAt: "2026-03-18T06:30:00.000Z",
      updatedAt: "2026-03-18T07:05:00.000Z",
      importSource: "manual",
      accountSource: "shanyouxiang",
      sourceRawPayload: "gamma@outlook.com----pass-111",
      lastUsedAt: "2026-03-18T06:59:00.000Z",
      lastResultStatus: "disabled",
      lastResultAt: "2026-03-18T07:01:00.000Z",
      lastErrorCode: "microsoft_unknown_recovery_email",
      skipReason: null,
      groupName: "failed-pool",
      disabledAt: "2026-03-18T07:01:00.000Z",
      disabledReason: "未知辅助邮箱：ga*****@genq.top",
    },
  ],
} satisfies AccountsPayload;

export const sampleApiKeys: ApiKeysPayload = {
  total: 2,
  page: 1,
  pageSize: 20,
  summary: {
    active: 1,
    revoked: 1,
  },
  groups: ["linked", "ops"],
  rows: [
    {
      id: 1,
      accountId: 2,
      microsoftEmail: "beta@outlook.com",
      groupName: "linked",
      apiKeyMasked: "tvly-****-af3x",
      apiKeyPrefix: "tvly-prod",
      status: "active",
      extractedAt: "2026-03-18T07:14:00.000Z",
      lastVerifiedAt: "2026-03-18T07:16:00.000Z",
    },
    {
      id: 2,
      accountId: 7,
      microsoftEmail: "omega@outlook.com",
      groupName: "ops",
      apiKeyMasked: "tvly-****-mm9p",
      apiKeyPrefix: "tvly-sbx",
      status: "revoked",
      extractedAt: "2026-03-17T15:40:00.000Z",
      lastVerifiedAt: "2026-03-18T00:10:00.000Z",
    },
  ],
};

export const sampleProxies: ProxyPayload = {
  settings: {
    subscriptionUrl: "https://example.com/subscription.yaml",
    groupName: "Auto",
    routeGroupName: "Global",
    checkUrl: "https://www.gstatic.com/generate_204",
    timeoutMs: 1000,
    maxLatencyMs: 480,
    apiPort: 9090,
    mixedPort: 7890,
    serverHost: "127.0.0.1",
    serverPort: 9090,
    defaultRunMode: "headed",
    defaultNeed: 5,
    defaultParallel: 2,
    defaultMaxAttempts: 9,
  },
  selectedName: "Tokyo-01",
  nodes: [
    {
      id: 1,
      nodeName: "Tokyo-01",
      isSelected: true,
      lastStatus: "active",
      lastLatencyMs: 184,
      lastEgressIp: "34.91.22.10",
      lastCountry: "Japan",
      lastCity: "Tokyo",
      lastOrg: "ExampleNet",
      lastCheckedAt: "2026-03-18T07:20:00.000Z",
      lastSelectedAt: "2026-03-18T07:18:00.000Z",
      success24h: 8,
    },
    {
      id: 2,
      nodeName: "Seoul-02",
      isSelected: false,
      lastStatus: "warning",
      lastLatencyMs: 531,
      lastEgressIp: "52.11.12.44",
      lastCountry: "South Korea",
      lastCity: "Seoul",
      lastOrg: "TransitCloud",
      lastCheckedAt: "2026-03-18T07:19:00.000Z",
      lastSelectedAt: null,
      success24h: 2,
    },
  ],
};

export const sampleExtractorSettings: AccountExtractorSettings = {
  extractorZhanghaoyaKey: "zhya-demo-key-001",
  extractorShanyouxiangKey: "shan-demo-key-001",
  extractorShankeyunKey: "shanke-demo-key-001",
  extractorHotmail666Key: "hotmail666-demo-key-001",
  defaultAutoExtractSources: ["zhanghaoya", "hotmail666"],
  defaultAutoExtractQuantity: 1,
  defaultAutoExtractMaxWaitSec: 60,
  defaultAutoExtractAccountType: "outlook",
  availability: {
    zhanghaoya: true,
    shanyouxiang: true,
    shankeyun: true,
    hotmail666: false,
  },
};

export const sampleExtractorHistory: AccountExtractorHistoryPayload = {
  total: 4,
  page: 1,
  pageSize: 10,
  rows: [
    {
      id: 11,
      jobId: 17,
      provider: "zhanghaoya",
      accountType: "outlook",
      requestedUsableCount: 1,
      attemptBudget: 4,
      acceptedCount: 1,
      status: "accepted",
      errorMessage: null,
      rawResponse: "{\"Code\":200,\"Message\":\"Success\",\"Data\":\"fresh@outlook.com:pass-777\"}",
      maskedKey: "zhya********0001",
      startedAt: "2026-03-18T07:24:00.000Z",
      completedAt: "2026-03-18T07:24:01.000Z",
      items: [
        {
          id: 101,
          batchId: 11,
          provider: "zhanghaoya",
          rawPayload: "fresh@outlook.com:pass-777",
          email: "fresh@outlook.com",
          password: "pass-777",
          parseStatus: "parsed",
          acceptStatus: "accepted",
          rejectReason: null,
          importedAccountId: 51,
          createdAt: "2026-03-18T07:24:01.000Z",
        },
      ],
    },
    {
      id: 10,
      jobId: 17,
      provider: "shanyouxiang",
      accountType: "outlook",
      requestedUsableCount: 1,
      attemptBudget: 4,
      acceptedCount: 0,
      status: "rejected",
      errorMessage: "already_attempted",
      rawResponse: "retry@outlook.com----pass-123",
      maskedKey: "shan********0001",
      startedAt: "2026-03-18T07:23:00.000Z",
      completedAt: "2026-03-18T07:23:01.000Z",
      items: [
        {
          id: 100,
          batchId: 10,
          provider: "shanyouxiang",
          rawPayload: "retry@outlook.com----pass-123",
          email: "retry@outlook.com",
          password: "pass-123",
          parseStatus: "parsed",
          acceptStatus: "rejected",
          rejectReason: "already_attempted",
          importedAccountId: 3,
          createdAt: "2026-03-18T07:23:01.000Z",
        },
      ],
    },
    {
      id: 9,
      jobId: 17,
      provider: "shankeyun",
      accountType: "outlook",
      requestedUsableCount: 1,
      attemptBudget: 4,
      acceptedCount: 1,
      status: "accepted",
      errorMessage: null,
      rawResponse: "fresh-sk@outlook.com----pass-999--------refresh-token----client-id",
      maskedKey: "shan********0002",
      startedAt: "2026-03-18T07:22:00.000Z",
      completedAt: "2026-03-18T07:22:01.000Z",
      items: [
        {
          id: 99,
          batchId: 9,
          provider: "shankeyun",
          rawPayload: "fresh-sk@outlook.com----pass-999--------refresh-token----client-id",
          email: "fresh-sk@outlook.com",
          password: "pass-999",
          parseStatus: "parsed",
          acceptStatus: "accepted",
          rejectReason: null,
          importedAccountId: 52,
          createdAt: "2026-03-18T07:22:01.000Z",
        },
      ],
    },
    {
      id: 8,
      jobId: 17,
      provider: "hotmail666",
      accountType: "outlook",
      requestedUsableCount: 1,
      attemptBudget: 4,
      acceptedCount: 0,
      status: "insufficient_stock",
      errorMessage: "剩余次数不足，当前剩余: 0",
      rawResponse: "{\"success\":false,\"message\":\"剩余次数不足，当前剩余: 0\"}",
      maskedKey: "hotm********0001",
      startedAt: "2026-03-18T07:21:00.000Z",
      completedAt: "2026-03-18T07:21:01.000Z",
      items: [],
    },
  ],
};
